GEMINI_API_KEY="AIzaSyAKkVTd5Ssl2YXqsnNkk1i7J5Aj-GgXCvw"
META_AI_API_KEY="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"

[mysql]
host="gateway01.us-east-1.prod.aws.tidbcloud.com"
port=4000
user="2akcwuNvYGJ1yHg.root"
password="5M4nFmFgTdQSXTIJ"
database="avaliacoes_ia"