GEMINI_API_KEY="AIzaSyBgxT9607fZdnmjwIZp4Uz0T3EYVBsXmiI"
META_AI_API_KEY="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"

[mysql]
host="gateway01.us-east-1.prod.aws.tidbcloud.com"
port=4000
user="2akcwuNvYGJ1yHg.root"
password="5M4nFmFgTdQSXTIJ"
database="avaliacoes_ia"
